openapi: 3.0.0
info:
  title: Product API
  version: v1
paths:
  /products:
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  maxLength: 20
                  description: Unique product code
                name:
                  type: string
                  maxLength: 50
                  description: Product name
                description:
                  type: string
                  description: Product description
              required:
                - code
                - name
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID of the created product
    get:
      summary: List products with pagination
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: Page number (default: 1)
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
          description: Number of products per page (default: 10)
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          description: Product code
                        name:
                          type: string
                          description: Product name
                  totalItems:
                    type: integer
                    description: Total number of products
                  totalPages:
                    type: integer
                    description: Total number of pages
                  page:
                    type: integer
                    description: Current page number
                  pageSize:
                    type: integer
                    description: Number of products per page
  /products/{id}:
    patch:
      summary: Update an existing product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 50
                  description: Product name
                description:
                  type: string
                  description: Product description
              required:
                - name
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID of the updated product
    delete:
      summary: Delete a product (soft delete)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to delete
      responses:
        '204':
          description: Product deleted successfully (soft delete)
components:
  schemas:
    Product:
      type: object
      properties:
        code:
          type: string
          maxLength: 20
          description: Unique product code
        name:
          type: string
          maxLength: 50
          description: Product name
        description:
          type: string
          description: Product description
        deleted:
          type: boolean
          description: Soft delete flag